services:

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ~/redis/data:/data
  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander
    restart: always
    depends_on:
      - redis
    ports:
      - 8081:8081
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
#  minio:
#    image: minio/minio:latest
#    environment:
#      MINIO_ACCESS_KEY_FILE: access_key
#      MINIO_SECRET_KEY_FILE: secret_key
#    volumes:
#      - minio-volume:/data
volumes:
  redis:
    name: "redis"
  redis-config:
    name: "redis-config"
  postgres:
    name: "postgres"

networks:
  redis:
    driver: bridge
  postgres:
    driver: bridge
  app:
    driver: bridge